# Generated by Django 4.2.8 on 2023-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_notes",
            field=models.TextField(default="To be added", max_length=250),
        ),
    ]
