# Generated by Django 4.2.8 on 2023-12-19 16:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0006_profile_avatar_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="you@example.com", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="1-111-111-1111", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
