# Generated by Django 4.2.8 on 2023-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0007_profile_email_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="quote_source",
            field=models.CharField(default="Anon", max_length=100),
        ),
    ]
