# Generated by Django 4.2.8 on 2023-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0008_profile_quote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="quote_author",
            field=models.CharField(default="Anon", max_length=150),
        ),
    ]
