# Generated by Django 4.2.8 on 2023-12-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0012_task_date_completed_task_date_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
